### ISSUE TITLE
Why should I use the webserver-api?

### ISSUE THREAD

**Issue by dojo90** [siemens/simatic-s7-webserver-api#11]
First of all, I would like to thank siemens for finally realising that `open source` is the way forward.

I would like to know what the added value of this interface is compared to the OPC interface? Or why should I use this interface at all? Do I have a better performance compared to OPC?

_As a small side note. Maybe you(siemens) will manage to make your TIA projects compatible with git as well. Unfortunately, your sales people advertise ignorance and the fact that git is not worth mentioning in order to integrate it. 🤦‍♂️_

**Comment by KircMax** [comment]
Hi @dojo90,

I could expect multiple customers to have troubles making a decision about this - we will also add a chapter in the readme for that... To give you an answer:

To be honest, I'm not sure that a hard comparison between OPC UA and the Web API is that useful. 

Both flavors of open interoperability to other systems are fully supported and continuously developed by Siemens. Some features are supported by either one or the other, and for the features that are supported by both, it's ultimately up to your preferences. 

**OPC UA** is a widely known and supported **industry standard** developed and maintained by the **OPC Foundation** that was created for a variety of **Plug&Play** communication use cases. Quite in the sense of a strategic orientation of a cross vendor **interoperability**. The focus here is set on data exchange in the most interoperable and efficient way (subscriptions, companion specifications, …). This also includes **plc-to-plc-communication** via OPC Client and Server. 

The focus of the **Web API** rather is **maintenance**, **problem finding** and offering the possibility to implement small and medium-sized **Web Applications**. This API is based on standardized **JSON-RPC** via **HTTPS** communication with a Simatic-specific data model.  

Unfortunately a general performance expectation is hard to calculate as this is highly dependent on use cases, requirements, the given environment and the used system.

For feature-specific details and evaluation of what best suits your use case, please also take a look into the manuals of OPC UA or the Webserver.
